language: c++
compiler:
    - gcc
os:
    - linux
dist: trusty
addons:
    apt:
        packages:
            - binutils
            - lcov
install:
    - export PATH=$HOME/.local/bin:$PATH
    - pip install cpp-coveralls pyyaml requests[security] --user `whoami`
    - ./setup.sh --coverage
script:
    - cd build
    - make -j2 liblw-tests
    - Debug/liblw-tests
after_success:
    - cd $TRAVIS_BUILD_DIR
    - coveralls --exclude external --exclude tests --root $TRAVIS_BUILD_DIR --build-root $TRAVIS_BUILD_DIR/build --gcov gcov-5 --gcov-options '\-lp'
